<?php
/** op-layout-flexbox:/template/404.phtml
 *
 * @created     2023-05-09
 * @version     1.0
 * @package     op-layout-flexbox
 * @author      Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright   Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP;

?>
<div class="message">
	<h1>Page not found: 404 Error</h1>
	<p>The page you are looking for could not be found.</p>
</div>
<div class="details">
	timestamp: <?= OP()->Timestamp() ?>
</div>
