<?php
/** op-layout-flexbox:/template/404.phtml
 *
 * @created     2023-05-09
 * @version     1.0
 * @package     op-layout-flexbox
 * @author      Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright   Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP;

?>
<div class="message">
	<h1>Page not found: 404 Error</h1>
	<img src="<?= OP::Path('app:/img/bird.png') ?>"/>
	<p>
		Once upon a midnight dreary,<br>
		while I pondered weak and weary,<br>
		Over many a quaint and curious<br>
		volume of forgotten lore,<br>
		<br>
		While I nodded, nearly napping,<br>
		suddenly there came a tapping,<br>
		As of some one gently rapping,<br>
		rapping at my chamber door.<br>
		<br>
		`'Tis some visitor,' I muttered, <br>
		`tapping at my chamber door -<br>
		Only this, and nothing more.'<br>
		<br>
	</p>
</div>
<div class="details">
	timestamp: <?= OP()->Timestamp() ?>
</div>
