<?php
/** op-layout-white:/template/404.phtml
 *
 * @created   2020-01-08
 * @version   1.0
 * @package   op-layout-white
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2020-01-08
 */
namespace OP;

?>
<div class="message">
	<h1>Page not found: 404 Error</h1>
	<img src="<?= ConvertURL('app:/img/bird.png') ?>"/>
	<p>
		Once upon a midnight dreary,<br>
		while I pondered weak and weary,<br>
		Over many a quaint and curious<br>
		volume of forgotten lore,<br>
		<br>
		While I nodded, nearly napping,<br>
		suddenly there came a tapping,<br>
		As of some one gently rapping,<br>
		rapping at my chamber door.<br>
		<br>
		`'Tis some visitor,' I muttered, <br>
		`tapping at my chamber door -<br>
		Only this, and nothing more.'<br>
		<br>
	</p>
</div>
<div class="details">
	timestamp: <?= Env::Timestamp() ?>
</div>
