<?php
/** op-layout-flexbox:/template/copyright.phtml
 *
 * @created     2023-12-29
 * @version     1.0
 * @package     op-layout-flexbox
 * @author      Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright   Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP;

?>

<div class="copyright">
	Copyright 2023 All right reserved onepiece-framework.
</div>
