<?php
/**
 * layout-white:/html.phtml
 *
 * @creation  2016-11-22
 * @version   1.0
 * @package   layout-white
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

/** use
 *
 * @created   2019-11-22
 */
use OP\UNIT\App;

?>
<!doctype html>
<html lang="<?= Env::Language() ?>">
	<head>
		<?php
		//	head
		App::Template('layout/head.phtml');
		?>
	</head>
	<body id="body" class="body">
		<div id="head-area">
			<?php
			//	Header area
			App::Template('layout/header.phtml');
			App::Template('layout/menu/top.phtml');
			?>
		</div>
		<div id="body-area">
			<div>
				<?php
				//	Left menu
				App::Template('layout/menu/left.phtml');
				?>
			</div>
			<div id="content-area" class="content-area">
				<?php
				//	Main content
				App::Content();
				?>
			</div>
			<div>
				<?php
				//	Right menu
				App::Template('layout/menu/right.phtml');
				?>
			</div>
		</div>
		<div id="foot-area">
			<?php
			//	Footer area
			App::Template('layout/menu/bottom.phtml');
			App::Template('layout/footer.phtml');
			?>
		</div>
	</body>
</html>
