<?php
/** op-layout-white:/html.phtml
 *
 * @created   2016-11-22
 * @version   1.0
 * @package   op-layout-white
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

/** use
 *
 */

?>
<!doctype html>
<html lang="<?= Env::Language() ?>">
	<head>
		<?php
		//	head
		Template('layout/head.phtml');
		?>
	</head>
	<body id="body" class="body">
		<div id="header-area">
			<?php
			//	Header area
			Template('layout/header.phtml');
			Template('layout/menu/top.phtml');
			?>
		</div>
		<div id="body-area">
			<div>
				<?php
				//	i18n language list.
				Template('layout/i18n_language_list.phtml');
				?>
			</div>
			<div>
				<?php
				//	Left menu
				Template('layout/menu/left.phtml');
				?>
			</div>
			<div id="content-area" class="content-area">
				<?php
				//	Main content
				Content();
				?>
			</div>
			<div>
				<?php
				//	Right menu
				Template('layout/menu/right.phtml');
				?>
			</div>
		</div>
		<div id="footer-area">
			<?php
			//	Footer area
			Template('layout/menu/bottom.phtml');
			Template('layout/footer.phtml');
			?>
		</div>
	</body>
</html>
