<?php
/** op-layout-white:/html.phtml
 *
 * @created   2016-11-22
 * @version   1.0
 * @package   op-layout-white
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

?>
<!doctype html>
<html lang="en">
    <head>
        <?php
        //	head
        Template('layout/head.phtml');
        ?>
    </head>
    <body id="body" class="body">
        <div id="header-area"><?php Template('layout/header.phtml') ?></div>
        <div id="body-area">
            <div id="menu-top"><?php Template('layout/menu/top.phtml') ?></div>
            <div id="menu-middle">
                <div id="menu-left" ><?php Template('layout/menu/left.phtml') ?></div>
                <div id="content"   ><main role="main"><?php Content() ?></main></div>
                <div id="menu-right"><?php Template('layout/menu/right.phtml') ?></div>
            </div>
            <div id="menu-bottom"><?php Template('layout/menu/bottom.phtml') ?></div>
        </div>
        <div id="footer-area"><?php Template('layout/footer.phtml') ?></div>
    </body>
</html>
